Introduce denv and fix stderr messages
Previously, we had separate scripts to start and to exec the native dev
Docker container. Now, we've consolidated those into the ~/bin/denv
utility.

Additionally, this commit fixes a bunch of echos that should have been
going to stderr.

diff --git a/environments/ubuntu-common/refresh-conda-env b/environments/ubuntu-common/refresh-conda-env
--- a/environments/ubuntu-common/refresh-conda-env
+++ b/environments/ubuntu-common/refresh-conda-env
@@ -79,7 +79,7 @@ ANSIBLE_LOCALHOST_WARNING=False ANSIBLE_INVENTORY_UNPARSED_WARNING=False ansible
 # failed_when: the return code is nonzero
 
 if [[ $rc -ne 0 ]]; then
-  echo -e "[ERROR]: The Ansible playbook failed with return code ${rc}."
+  echo -e "[ERROR]: The Ansible playbook failed with return code ${rc}." >&2
   exit $rc
 fi
 
